# Generated by Django 5.2.5 on 2025-09-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='salesperson'),
        ),
    ]
